version: '3.8'

services:
  redis:
    image: redis:$TAG
    container_name: redis_server
    ports:
      - "${FORWARD_REDIS_PORT:-6379}:6379"  # Change the first "6379" to your desired host port if needed
    environment:
      - REDIS_PASSWORD={$REDIS_PASSWORD}  # Replace 'yourpassword' with your desired password
    command: [
      "redis-server",
      "--requirepass", "$REDIS_PASSWORD",  # Ensure the password matches the one set above
      "--port", "6379"  # Change '6379' to your desired port if different
    ]
    volumes:
      - redis_data:/data

volumes:
  redis_data:
